#pragma once

#include "Kismet/BlueprintFunctionLibrary.h"
#include "ShockAudioLibrary.generated.h"

class UAudioComponent;
class USceneComponent;
class USoundBase;
class UWorld;

/** Runtime bridge to assets generated by tools/ue5/import_audio.py. */
UCLASS()
class BIOSHOCKRUNTIME_API UShockAudioLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	/** Load /Game/BioShockAudio/1-Medical/Cues/<CueName>. */
	UFUNCTION(BlueprintPure, Category="BioShock|Audio")
	static USoundBase* LoadCue(FName CueName);

	/** Load an exact SourceClassName + event alias generated from SoundEventReader data. */
	UFUNCTION(BlueprintPure, Category="BioShock|Audio")
	static USoundBase* LoadEventCue(FName SourceClassName, FName EventName);

	/** Spawn a cue attached to a pawn/weapon component. Null when the imported asset is absent. */
	static UAudioComponent* SpawnCueAttached(
		FName CueName,
		USceneComponent* AttachTo,
		FName SocketName = NAME_None);

	/** Spawn an exact event alias attached to a component. */
	static UAudioComponent* SpawnEventAttached(
		FName SourceClassName,
		FName EventName,
		USceneComponent* AttachTo);

	/** Spawn a positional cue at a world location. */
	static UAudioComponent* SpawnCueAtLocation(UWorld* World, FName CueName, FVector Location);

	/** Headless verification: deterministic generated object path for a cue. */
	UFUNCTION(BlueprintPure, Category="BioShock|Audio")
	static FString CueObjectPath(FName CueName);

	/** Headless verification: deterministic generated object path for an event alias. */
	UFUNCTION(BlueprintPure, Category="BioShock|Audio")
	static FString EventObjectPath(FName SourceClassName, FName EventName);
};
