using System.Numerics;
using BioShockStudio.Core.Packages;

namespace BioShockStudio.Core.Level;

/// <summary>
/// How far a piece of reconstruction got. A level that reports honestly is more useful than one
/// that reports success, so nothing in this layer throws away the difference.
/// </summary>
public enum ResolutionStatus
{
    /// <summary>Everything needed was found and decoded.</summary>
    Resolved,

    /// <summary>Some of it was found; what is missing is named.</summary>
    Partial,

    /// <summary>The reference exists but points outside what this package can supply.</summary>
    External,

    /// <summary>Nothing of the kind was found. Not an error — most actors have no mesh.</summary>
    Absent,

    /// <summary>A reference was found and did not resolve, or a decode failed.</summary>
    Failed,
}

/// <summary>
/// A stable identity for one shipped object: the package it lives in, its export index, its class
/// and its name. Names are not unique within a package and classes repeat across packages, so
/// deduplication and debugging both need all four.
/// </summary>
public readonly record struct SourceId(string Package, int ExportIndex, string ClassName, string ObjectName)
{
    public override string ToString() => $"{Package}:{ExportIndex} {ClassName} {ObjectName}";

    /// <summary>A filesystem- and asset-name-safe key, unique within a package.</summary>
    public string Key => $"{ClassName}_{ObjectName}_{ExportIndex}";
}

/// <summary>A reference from an actor to an asset, with what became of it.</summary>
public sealed record AssetReference
{
    public required PackageIndex Index { get; init; }
    public required string ObjectName { get; init; }
    public required string ClassName { get; init; }

    /// <summary>Where the reference was found: the actor's own properties, or its class defaults.</summary>
    public required string Origin { get; init; }

    /// <summary>Set when the reference resolves to an export in this package.</summary>
    public SourceId? Source { get; init; }

    public ResolutionStatus Status =>
        Index.IsNull ? ResolutionStatus.Absent
        : Source is not null ? ResolutionStatus.Resolved
        : Index.IsImport ? ResolutionStatus.External
        : ResolutionStatus.Failed;

    public override string ToString() => $"{ObjectName} [{ClassName}] ({Status})";
}

/// <summary>
/// The explicitly typed navigation subset of an actor's property graph. The rest remains in
/// <see cref="LevelActor.Properties"/> until a concrete UE5 mapping has evidence.
/// </summary>
public sealed record NavigationActorData
{
    /// <summary>Edges named by the serialised <c>PathList</c> object-reference array.</summary>
    public IReadOnlyList<AssetReference> PathLinks { get; init; } = [];

    /// <summary>Nodes named by the serialised <c>AutoGeneratedFlyingPathNodes</c> array.</summary>
    public IReadOnlyList<AssetReference> AutoGeneratedFlyingPathNodes { get; init; } = [];

    /// <summary>Value of the declared float property, where present.</summary>
    public float? PathCollisionRadius { get; init; }

    /// <summary>
    /// Whether the <c>bIsAutoGenerated</c> Bool tag was serialised. Its Bool payload convention is
    /// retained raw, so this records tag presence rather than inventing a false/default value.
    /// </summary>
    public bool AutoGeneratedFlagSerialized { get; init; }
}

/// <summary>
/// The object graph named by a placed <c>Script</c> actor's <c>Actions</c> property. This records
/// identity only: interpreting the action classes as gameplay or Blueprint nodes needs separate
/// evidence.
/// </summary>
public sealed record ScriptActorData
{
    /// <summary>Referenced action objects, in their serialised order.</summary>
    public IReadOnlyList<AssetReference> Actions { get; init; } = [];

    /// <summary>True only when the compact count and all references consumed the complete value.</summary>
    public required bool Complete { get; init; }
}

/// <summary>
/// The effect-template identities named by a placed actor's <c>Emitters</c> property. Parameter
/// semantics remain in the referenced template and are not inferred from the placement array.
/// </summary>
public sealed record EmitterActorData
{
    public IReadOnlyList<EmitterTemplateData> Templates { get; init; } = [];
    public required bool Complete { get; init; }
}

/// <summary>UE2's <c>Range</c> struct: an inclusive float interval, serialised as a nested tagged list.</summary>
public readonly record struct FloatRange(float Min, float Max);

/// <summary>UE2's <c>RangeVector</c> struct: one <see cref="FloatRange"/> per axis.</summary>
public readonly record struct AxisRange(FloatRange X, FloatRange Y, FloatRange Z);

/// <summary>One key of a <c>{ RelativeTime, RelativeSize }</c>-shaped curve array (e.g. <c>SizeScale</c>).</summary>
public readonly record struct FloatCurveKey(float RelativeTime, float Value);

/// <summary>One key of a <c>{ RelativeTime, Color }</c>-shaped curve array (e.g. <c>ColorScale</c>).</summary>
public readonly record struct ColorCurveKey(float RelativeTime, LightColor Color);

/// <summary>One key of a <c>{ RelativeTime, RelativeVelocity }</c>-shaped curve array (<c>VelocityScale</c>).</summary>
public readonly record struct VectorCurveKey(float RelativeTime, Vector3 Value);

/// <summary>
/// The byte-backed typed subset of one referenced emitter template — enough to place, size, move
/// and colour a particle without inventing a value the game did not ship. Eleven single-byte fields
/// (<c>Blending</c>, <c>CoordinateSystem</c>, ...) are carried as their raw byte because their enum
/// declarations are not in anything this project has read; see <c>docs/research/effects.md</c> §6.
/// <c>SubdivisionScale</c> and <c>RevolutionScale</c> (6 and 1 shipped hits) remain undecoded.
/// </summary>
public sealed record EmitterTemplateData
{
    public required AssetReference Source { get; init; }
    public AssetReference? Material { get; init; }
    public int? MaxParticles { get; init; }
    public float? ParticlesPerSecond { get; init; }
    public float? InitialParticlesPerSecond { get; init; }
    public bool? AutomaticInitialSpawning { get; init; }
    public bool? RespawnDeadParticles { get; init; }

    public FloatRange? LifetimeRange { get; init; }

    public AxisRange? StartSizeRange { get; init; }
    public bool? UniformSize { get; init; }
    public bool? UseSizeScale { get; init; }
    public bool? UseRegularSizeScale { get; init; }
    public IReadOnlyList<FloatCurveKey>? SizeScale { get; init; }

    public AxisRange? StartVelocityRange { get; init; }
    public Vector3? Acceleration { get; init; }
    public IReadOnlyList<VectorCurveKey>? VelocityScale { get; init; }

    public AxisRange? StartLocationRange { get; init; }
    public Vector3? StartLocationOffset { get; init; }

    /// <summary>Byte enum; meaning `UNKNOWN` (docs/research/effects.md §6).</summary>
    public byte? StartLocationShape { get; init; }

    public AxisRange? StartSpinRange { get; init; }
    public AxisRange? SpinsPerSecondRange { get; init; }
    public bool? SpinParticles { get; init; }

    public bool? UseColorScale { get; init; }
    public IReadOnlyList<ColorCurveKey>? ColorScale { get; init; }

    /// <summary>Byte enum; meaning `UNKNOWN` (docs/research/effects.md §6).</summary>
    public byte? Blending { get; init; }

    /// <summary>Byte enum; meaning `UNKNOWN` (docs/research/effects.md §6).</summary>
    public byte? CoordinateSystem { get; init; }

    public int? TextureUSubdivisions { get; init; }
    public int? TextureVSubdivisions { get; init; }

    /// <summary><c>MeshEmitter</c> only — its visual, in place of the other classes' sprite texture.</summary>
    public AssetReference? StaticMesh { get; init; }

    /// <summary><c>MultipleRibbonEmitter</c>/<c>RibbonEmitter</c> only — the per-segment analogues of <see cref="SizeScale"/>/<see cref="ColorScale"/>.</summary>
    public IReadOnlyList<FloatCurveKey>? SegmentSizeScale { get; init; }
    public IReadOnlyList<ColorCurveKey>? SegmentColorScale { get; init; }

    /// <summary>Whether its ordinary tagged-property list walked cleanly; unsupported fields remain raw.</summary>
    public required bool PropertiesComplete { get; init; }
}

/// <summary>One placed world object.</summary>
/// <summary>
/// UE2's <c>FPointRegion</c>: where in the compiled world an actor stands.
/// </summary>
/// <remarks>
/// <para>
/// <c>CONFIRMED_BYTES</c>, 23 Aug 2026. The property is a nested tagged list whose walk consumes
/// all 30 bytes, giving <c>Zone</c>, <c>iLeaf</c> and <c>ZoneNumber</c> - the same three fields
/// UE2 declares.
/// </para>
/// <para>
/// <b>It cross-checks itself.</b> <c>iLeaf</c> indexes the BSP leaves, each of which carries its
/// own zone, so <see cref="ZoneNumber"/> and <c>Leaves[iLeaf].Zone</c> state the same fact twice
/// from different bytes. They agree on 96,136 of 96,376 actors (99.75%) game-wide.
/// </para>
/// <para>
/// <b><see cref="Leaf"/> of 0 means "no leaf assigned", not leaf index 0</b> - 20,159 actors carry
/// it and only 760 happen to match leaf 0's zone.
/// </para>
/// </remarks>
public sealed record ActorRegion
{
    /// <summary>Index into the compiled world's leaf array, or 0 for "none".</summary>
    public required int Leaf { get; init; }

    /// <summary>The zone the actor is in.</summary>
    public required byte ZoneNumber { get; init; }

    /// <summary>True when <see cref="Leaf"/> actually names a leaf.</summary>
    public bool HasLeaf => Leaf != 0;
}

/// <summary>Typed collision and trigger fields carried by region/volume actors.</summary>
public sealed record RegionActorData
{
    public ActorScaleData? MainScale { get; init; }
    public ActorScaleData? PostScale { get; init; }
    public bool? BlockActors { get; init; }
    public bool? BlockHavok { get; init; }
    public bool? BlockNonZeroExtentTraces { get; init; }
    public bool? BlockPlayers { get; init; }
    public bool? BlockZeroExtentTraces { get; init; }
    public bool? CollideActors { get; init; }
    public bool? Disabled { get; init; }
    public bool? Enabled { get; init; }
    public bool? TriggerOnlyOnce { get; init; }
    public bool? TriggerWhenNotSeen { get; init; }
    public float? CollisionRadius { get; init; }
    public float? CollisionHeight { get; init; }
    public float? MinimumDistance { get; init; }
    public string? TriggeredBy { get; init; }
    public IReadOnlyList<string> TriggerOnlyByLabels { get; init; } = [];
    public IReadOnlyList<string> TriggeredByFilter { get; init; } = [];
    public IReadOnlyList<AssetReference> TriggerOnlyByClasses { get; init; } = [];
    public AssetReference? WaterMesh { get; init; }
    public byte? WaterAxis { get; init; }
    public float? MovingInWaterPenalty { get; init; }
    public int? Priority { get; init; }
    public bool? NoDelete { get; init; }
    public ZoneActorData? Zone { get; init; }
    public bool Complete { get; init; }
}

public sealed record ActorScaleData
{
    public required Vector3 Scale { get; init; }
    public required float SheerRate { get; init; }
    public required byte SheerAxis { get; init; }
}

public sealed record ZoneAmbientData
{
    public Vector3? VectorHigh { get; init; }
    public LightColor? ColorHigh { get; init; }
    public float? ColorHighMultiplier { get; init; }
    public float? ColorLowMultiplier { get; init; }
    public float? ContrastPower { get; init; }
    public float? XGroundRatio { get; init; }
}

public sealed record ZoneFogData
{
    public bool? Enabled { get; init; }
    public bool? Clip { get; init; }
    public LightColor? Color { get; init; }
    public float? Start { get; init; }
    public float? End { get; init; }
    public float? MaxContribution { get; init; }
}

public sealed record ZoneActorData
{
    public ZoneAmbientData? CurrentAmbient { get; init; }
    public ZoneAmbientData? NormalPressureAmbient { get; init; }
    public ZoneAmbientData? HighPressureAmbient { get; init; }
    public ZoneAmbientData? LowPressureAmbient { get; init; }
    public ZoneFogData? CurrentFog { get; init; }
    public ZoneFogData? NormalFog { get; init; }
    public ZoneFogData? HighFog { get; init; }
    public byte? ReverbType { get; init; }
    public string? MapUiRegion { get; init; }
    public string? PressureRegion { get; init; }
    public float? PressureEffectsDuration { get; init; }
    public float? TimeLastPressureChange { get; init; }
    public IReadOnlyList<string> SpawnZones { get; init; } = [];
    public IReadOnlyList<string> EffectsContexts { get; init; } = [];
    public IReadOnlyList<AssetReference> ManualExcludes { get; init; } = [];
}

/// <summary>Typed AI population declaration carried by an aggressor spawner.</summary>
public sealed record SpawnerActorData
{
    public string? GlobalPatrol { get; init; }
    public string? InitialPatrol { get; init; }
    public string? RepopulationPatrol { get; init; }
    public string? InitialLabel { get; init; }
    public IReadOnlyList<string> GlobalAiTypes { get; init; } = [];
    public IReadOnlyList<string> InitialAiTypes { get; init; } = [];
    public IReadOnlyList<string> RepopulationAiTypes { get; init; } = [];
    public IReadOnlyList<string> OverriddenAiArchetypeNames { get; init; } = [];
    public IReadOnlyList<string> SpawnZones { get; init; } = [];
    public bool Complete { get; init; }
}

public sealed record ProjectorActorData
{
    public AssetReference? Material { get; init; }
    public Vector3? Tile { get; init; }
    public int? MaxTraceDistance { get; init; }
    public int? ZBiasOverride { get; init; }
    public float? ScaleInTime { get; init; }
    public PropertyValues.ProjectorGradient? AngleGradient { get; init; }
    public bool? ProjectOnBackfaces { get; init; }
    public bool? ProjectStaticMesh { get; init; }
    public bool? ProjectSkeletalMesh { get; init; }
    public bool? ShouldBeAttached { get; init; }
    public bool Complete { get; init; }
}

public sealed record HavokForceActorData
{
    public required AssetReference ForceType { get; init; }
    public required AssetReference ForceShape { get; init; }
    public AssetReference? ForceFilter { get; init; }
    public bool Complete => ForceType.Status != ResolutionStatus.Failed
                            && ForceShape.Status != ResolutionStatus.Failed
                            && ForceFilter?.Status != ResolutionStatus.Failed;
}

public sealed record HavokConstraintActorData
{
    public required AssetReference AttachedActorA { get; init; }
    public AssetReference? AttachedActorB { get; init; }
    public bool? DisableCollisions { get; init; }
    public bool? UseLimitedHinge { get; init; }
    public float? LimitedHingeFrictionValue { get; init; }
    public float? LimitedHingeTauFactor { get; init; }
    public bool Complete => AttachedActorA.Status != ResolutionStatus.Failed
                            && AttachedActorB?.Status != ResolutionStatus.Failed;
}

public sealed record MapUiMarkerData
{
    public required string LayerName { get; init; }
    public required string ScaleMarkerName { get; init; }
    public required IReadOnlyList<string> RegionNames { get; init; }
    public bool Complete { get; init; }
}

public sealed record VendingActorData
{
    public required string VendingTableName { get; init; }
    public required AssetReference VendingTable { get; init; }
    public required string HackInfoName { get; init; }
    public required AssetReference StaticMeshInstance { get; init; }
    public int? DestructionNotification { get; init; }
    public bool? CanBeHacked { get; init; }
    public bool Complete => VendingTable.Status != ResolutionStatus.Failed
                            && StaticMeshInstance.Status != ResolutionStatus.Failed;
}

public sealed record InteractionActorData
{
    public string? DoorLabel { get; init; }
    public string? HackInfoName { get; init; }
    public bool? Hackable { get; init; }
    public bool? ShowHudElements { get; init; }
}

public sealed record LevelInfoActorData
{
    public float? TimeSeconds { get; init; }
    public string? Title { get; init; }
    public string? FictionalMapName { get; init; }
    public AssetReference? Summary { get; init; }
    public AssetReference? SpawningManager { get; init; }
    public AssetReference? GlowSettings { get; init; }
    public AssetReference? ToneMapSettings { get; init; }
    public AssetReference? LevelAnimInfo { get; init; }
    public bool? HasPathNodes { get; init; }
    public Vector3? CameraLocationDynamic { get; init; }
    public Vector3? CameraLocationTop { get; init; }
    public Vector3? CameraLocationFront { get; init; }
    public Vector3? CameraLocationSide { get; init; }
    public UnrealRotator? CameraRotationDynamic { get; init; }
    public IReadOnlyList<AssetReference> NavigationPoints { get; init; } = [];
    public IReadOnlyList<PressureRegionData> PressureRegions { get; init; } = [];
    public IReadOnlyList<MapUiRegionData> MapUiRegions { get; init; } = [];
    public IReadOnlyList<MapHudRegionData> MapHudRegions { get; init; } = [];
    public IReadOnlyList<RequiredAnimationGroupData> RequiredAnimationGroups { get; init; } = [];
    public float? AmbientXGroundRatio { get; init; }
    public float? AmbientColorHighMultiplier { get; init; }
    public float? AmbientColorLowMultiplier { get; init; }
    public float? AmbientContrastPower { get; init; }
    public bool Complete { get; init; }
}

public sealed record ShockAiScoutData
{
    public IReadOnlyList<int> PointCollectionReferences { get; init; } = [];
    public Vector3? LastPathfindingOrigin { get; init; }
    public Vector3? LastPathfindingLocation { get; init; }
    public float? LastPathfindingTime { get; init; }
    public float? LastPathfindingFailedTime { get; init; }
    public float? LastPathfindingResult { get; init; }
    public AssetReference? Controller { get; init; }
    public bool? JumpCapable { get; init; }
    public bool? CanFly { get; init; }
    public bool? CanUseCeiling { get; init; }
    public float? LastValidAnchorTime { get; init; }
    public Vector3? Floor { get; init; }
    public AssetReference? HeadVolume { get; init; }
    public float? CollisionRadius { get; init; }
    public float? CollisionHeight { get; init; }
    public int? DestructionNotification { get; init; }
    public bool Complete { get; init; }
}

/// <summary>
/// The typed subset of a <c>Mover</c>/<c>ScriptableMover</c>: what triggers it and its start pose.
/// The keyframe path itself (<c>KeyPos</c>/<c>KeyRot</c>, indexed arrays serialised one element per
/// tagged property rather than a counted array) is deliberately not decoded here — see
/// <c>docs/research/interaction.md</c> for the census and why it's a separate, unverified piece.
/// </summary>
public sealed record MoverActorData
{
    /// <summary>The state this mover starts in, e.g. <c>BumpOpenTimed</c> — not <see cref="LevelActor.Tag"/>/<c>Label</c>, already read generically for every actor.</summary>
    public string? InitialState { get; init; }

    /// <summary>
    /// The comma-separated Script/Tag names that trigger this mover, in whatever order they were
    /// authored. Kept as the raw string, the same convention <see cref="RegionActorData.TriggeredBy"/>
    /// already uses — splitting is left to the caller since neither this project nor any reference
    /// source has confirmed the separator is always a plain comma.
    /// </summary>
    public string? TriggeredBy { get; init; }

    public Vector3? BasePos { get; init; }
    public UnrealRotator? BaseRot { get; init; }
    public float? MoveTime { get; init; }
    public float? StayOpenTime { get; init; }
    public bool? UseTriggered { get; init; }
    public bool? TriggerOnceOnly { get; init; }

    /// <summary>Byte enum; meaning `UNKNOWN` — not in `Bioshock1REMSDK-WIP--main`.</summary>
    public byte? MoverEncroachType { get; init; }

    /// <summary>Byte enum; meaning `UNKNOWN` — not in `Bioshock1REMSDK-WIP--main`.</summary>
    public byte? MoverGlideType { get; init; }

    public required bool Complete { get; init; }
}

public sealed record PressureRegionData(string Name, byte Pressure, float EffectsDuration);
public sealed record MapUiRegionData(string MapUiRegion, string HudRegion, bool? Revealed, float LastVisited);
public sealed record MapHudRegionData(string HudRegion, string Description);
public sealed record RequiredAnimationGroupData(string PackageName, string GroupName);

public sealed record LevelActor
{
    public required SourceId Source { get; init; }

    /// <summary>The actor's designer-facing name, from its <c>Label</c> property. Null when it has none.</summary>
    public string? Label { get; init; }

    /// <summary>The actor's <c>Tag</c>, which the game uses to group behaviour.</summary>
    public string? Tag { get; init; }

    /// <summary>
    /// Which zone the actor stands in, from its <c>Region</c> property. Null when it has none or
    /// the struct does not parse.
    /// </summary>
    /// <remarks>
    /// <c>Region</c> is UE2's <c>FPointRegion</c> and is present on <b>every</b> actor in the game -
    /// it was the single most common uninterpreted property before this. See
    /// <see cref="ActorRegion"/> for the cross-check that confirms it.
    /// </remarks>
    public ActorRegion? Region { get; init; }

    /// <summary>Typed gameplay-volume fields; null for actors outside the region/trigger family.</summary>
    public RegionActorData? RegionActor { get; init; }

    /// <summary>Exact training concept FNames declared by a <c>TrainingScript</c>.</summary>
    public IReadOnlyList<string> TrainingConcepts { get; init; } = [];

    /// <summary>Typed AI population declaration; null for actors without spawner properties.</summary>
    public SpawnerActorData? Spawner { get; init; }

    /// <summary>The reflection cubemap selected by a placed probe.</summary>
    public AssetReference? Cubemap { get; init; }
    public ProjectorActorData? Projector { get; init; }
    public HavokForceActorData? HavokForce { get; init; }

    /// <summary>The inventory/loot declaration selected by a placed pickup.</summary>
    public AssetReference? LootSlot { get; init; }
    public HavokConstraintActorData? HavokConstraint { get; init; }

    /// <summary>The occlusion volume/model selected by an anti-portal actor.</summary>
    public AssetReference? AntiPortal { get; init; }
    public MapUiMarkerData? MapUiMarker { get; init; }
    public VendingActorData? Vending { get; init; }
    public InteractionActorData? Interaction { get; init; }
    public LevelInfoActorData? LevelInfo { get; init; }
    public ShockAiScoutData? ShockAiScout { get; init; }

    /// <summary>Typed motion/trigger-wiring fields for <c>Mover</c> and <c>ScriptableMover</c>.</summary>
    public MoverActorData? Mover { get; init; }

    public required ActorTransform Transform { get; init; }

    /// <summary>The static mesh this actor draws, from its own properties or its class defaults.</summary>
    public AssetReference? StaticMesh { get; init; }

    /// <summary>The skeletal mesh this actor draws, if it is a skeletal actor.</summary>
    public AssetReference? SkeletalMesh { get; init; }

    /// <summary>Per-actor material overrides, from the <c>Skins</c> array.</summary>
    public IReadOnlyList<AssetReference> MaterialOverrides { get; init; } = [];

    /// <summary>The actor's parent, when it declares one — <c>Owner</c> or <c>Base</c>.</summary>
    public AssetReference? Attachment { get; init; }

    /// <summary>Typed navigation data when the actor carries the corresponding tagged-property family.</summary>
    public NavigationActorData? Navigation { get; init; }

    /// <summary>Structured action references when the actor serialised an <c>Actions</c> array.</summary>
    public ScriptActorData? ScriptActions { get; init; }

    /// <summary>Referenced effect templates when the actor serialised an <c>Emitters</c> array.</summary>
    public EmitterActorData? Emitters { get; init; }

    /// <summary>The <c>Brush</c> reference of a BSP actor: the <c>Model</c> holding its geometry.</summary>
    public AssetReference? Brush { get; init; }

    /// <summary>Groups the level editor put this actor in, from <c>OwnerGroups</c>.</summary>
    public IReadOnlyList<string> Groups { get; init; } = [];

    /// <summary>Every property the actor stored, by name, including ones nothing yet interprets.</summary>
    public required IReadOnlyList<UnrealProperty> Properties { get; init; }

    /// <summary>True when the property walk lost alignment, so the actor's data is incomplete.</summary>
    public required bool Truncated { get; init; }

    /// <summary>Bytes after the actor property terminator, including any class-specific suffix.</summary>
    public required byte[] Trailer { get; init; }

    /// <summary>The header field nothing has explained yet.</summary>
    public required int UnknownHeaderField { get; init; }

    public bool HasGeometry => StaticMesh?.Status is ResolutionStatus.Resolved or ResolutionStatus.External
                               || SkeletalMesh?.Status is ResolutionStatus.Resolved or ResolutionStatus.External
                               || Brush?.Status == ResolutionStatus.Resolved;

    public override string ToString() => $"{Source.ClassName} {Source.ObjectName} at {Transform.Location:0.#}";
}

/// <summary>
/// Everything the analyzer found in one level package: the actors, the assets they reference, and
/// what did not resolve.
/// </summary>
public sealed record LevelContext
{
    public required string PackageFile { get; init; }
    public required string PackageName { get; init; }
    public required int ExportCount { get; init; }
    public required int ImportCount { get; init; }
    public required int NameCount { get; init; }

    public required IReadOnlyList<LevelActor> Actors { get; init; }

    /// <summary>Exports carrying the actor header whose property list would not walk cleanly.</summary>
    public required IReadOnlyList<SourceId> FailedActors { get; init; }

    /// <summary>Distinct static meshes the level's actors reference, each with the actors that use it.</summary>
    public required IReadOnlyDictionary<SourceId, List<int>> StaticMeshUsage { get; init; }

    public required IReadOnlyDictionary<SourceId, List<int>> SkeletalMeshUsage { get; init; }

    /// <summary>References that named an object this package does not contain.</summary>
    public required IReadOnlyList<AssetReference> ExternalReferences { get; init; }

    /// <summary>References that resolved to nothing at all.</summary>
    public required IReadOnlyList<AssetReference> UnresolvedReferences { get; init; }

    /// <summary>Actor classes with no mesh of any kind, and how many there are of each.</summary>
    public required IReadOnlyDictionary<string, int> ClassesWithoutGeometry { get; init; }

    /// <summary>Property names seen on actors that nothing in this layer interprets, with counts.</summary>
    public required IReadOnlyDictionary<string, int> UninterpretedProperties { get; init; }

    public IEnumerable<LevelActor> WithStaticMesh => Actors.Where(a => a.StaticMesh is { Index.IsNull: false });
    public IEnumerable<LevelActor> WithSkeletalMesh => Actors.Where(a => a.SkeletalMesh is { Index.IsNull: false });
    public IEnumerable<LevelActor> Brushes => Actors.Where(a => a.Brush is { Index.IsNull: false });
    public IEnumerable<LevelActor> Lights => Actors.Where(a => a.Source.ClassName.EndsWith("Light", StringComparison.Ordinal));
    public IEnumerable<LevelActor> Volumes => Actors.Where(a => a.Source.ClassName.EndsWith("Volume", StringComparison.Ordinal));
}
