using System.Buffers.Binary;
using System.Numerics;
using BioShockStudio.Core.Packages;

namespace BioShockStudio.Core.Level;

/// <summary>
/// Builds a <see cref="LevelContext"/> from a map package: which exports are placed world objects,
/// where each one is, and what it draws.
/// <para>
/// Nothing here works from names. An actor is an actor because its payload carries the actor header,
/// which validates against the export table; its mesh is whatever its <c>StaticMesh</c> property or
/// its class's defaults point at; its position is its own <c>Location</c>. Filenames and class-name
/// prefixes are used only to describe what was found, never to decide it.
/// </para>
/// </summary>
public static class LevelAnalyzer
{
    /// <summary>Actor properties this layer reads. Everything else is counted as uninterpreted.</summary>
    private static readonly IReadOnlySet<string> Interpreted = new HashSet<string>(StringComparer.Ordinal)
    {
        "Location", "Rotation", "DrawScale", "DrawScale3D", "PrePivot",
        "StaticMesh", "Mesh", "SkeletalMesh", "Skins", "Brush",
        "Owner", "Base", "Label", "Tag", "OwnerGroups", "Region",
        "Actions",
        "bBlockActors", "bBlockHavok", "bBlockNonZeroExtentTraces", "bBlockPlayers",
        "bBlockZeroExtentTraces", "bCollideActors", "Disabled", "enabled", "bEnabled",
        "TriggerOnlyOnce", "TriggerWhenNotSeen", "CollisionRadius", "CollisionHeight",
        "MinimumDistance", "TriggeredBy", "TriggerOnlyByLabel", "triggeredByFilter",
        "TriggerOnlyByClass",
        "MainScale", "PostScale", "WaterMesh1", "Axis", "MovingInWaterPenalty", "Priority",
        "bNoDelete",
        "CurrentAmbientVectorHigh", "CurrentAmbientColorHigh", "CurrentAmbientColorHighMultiplier",
        "CurrentAmbientColorLowMultiplier", "CurrentAmbientContrastPower", "CurrentAmbientXGroundRatio",
        "NormalPressureAmbientVectorHigh", "NormalPressureAmbientColorHigh",
        "NormalPressureAmbientColorHighMultiplier", "NormalPressureAmbientContrastPower",
        "HighPressureAmbientVectorHigh", "HighPressureAmbientColorHigh",
        "HighPressureAmbientColorHighMultiplier", "HighPressureAmbientContrastPower",
        "LowPressureAmbientVectorHigh", "LowPressureAmbientColorHigh",
        "LowPressureAmbientColorHighMultiplier", "LowPressureAmbientContrastPower",
        "bDistanceFog", "bDistanceFogClip", "DistanceFogColor", "DistanceFogStart", "DistanceFogEnd",
        "MaxFogContribution", "NormalEnableDistanceFog", "NormalDistanceFogColor",
        "NormalDistanceFogStart", "NormalDistanceFogEnd", "NormalMaxFogContribution",
        "HighEnableDistanceFog", "HighDistanceFogColor", "HighDistanceFogStart", "HighDistanceFogEnd",
        "HighMaxFogContribution", "ReverbType", "MapUIRegion", "PressureRegion",
        "PressureEffectsDuration", "TimeLastPressureChange", "SpawnZones", "EffectsContexts",
        "ManualExcludes", "Concepts", "GlobalPatrol", "InitialPatrol", "RepopulationPatrol",
        "InitialLabel", "GlobalAITypes", "InitialAITypes", "RepopulationAITypes",
        "OverriddenAIArchetypeNames", "Cubemap", "Material", "Tile", "MaxTraceDistance",
        "ZBiasOverride", "ScaleInTime", "AngleGradient", "bProjectOnBackfaces",
        "bProjectStaticMesh", "bProjectSkeletalMesh", "bShouldBeAttached",
        "ForceType", "ForceShape", "ForceFilter", "LootSlot", "hkAttachedActorA",
        "hkAttachedActorB", "bDisableCollisions", "hkUseLimitedHinge",
        "hkLimitedHingeFrictionValue", "hkLimitedHingeTauFactor",
        "AntiPortal", "LayerName", "RegionNames", "ScaleMarkerName", "VendingTableName",
        "VendingTable", "HackInfoName", "StaticMeshInstance", "SendDestructionNotification",
        "bCanBeHacked", "DoorLabel", "bHackable", "bShowHudElements",
        "TimeSeconds", "Title", "Summary", "SpawningManager", "bHasPathNodes",
        "CameraLocationDynamic", "CameraLocationTop", "CameraLocationFront", "CameraLocationSide",
        "CameraRotationDynamic", "GlowSettings", "ToneMapSettings", "NavigationPointList",
        "PressureRegions", "MapUIRegions", "MapHUDRegions", "LabelFictionalMapName",
        "RequiredAnimationGroups", "LevelAnimInfo",
        "PointCollection", "LastPathfindingOrigin", "LastPathfindingLocation",
        "LastPathfindingTime", "LastPathfindingFailedTime", "LastPathfindingResult", "Controller",
        "bJumpCapable", "bCanFly", "bCanUseCeiling", "LastValidAnchorTime", "Floor", "HeadVolume",
        "InitialState", "BasePos", "BaseRot", "MoveTime", "StayOpenTime", "bUseTriggered",
        "bTriggerOnceOnly", "MoverEncroachType", "MoverGlideType",
        "PathList", "PathCollisionRadius", "AutoGeneratedFlyingPathNodes", "bIsAutoGenerated",
        "DoorPortal", "bLocked", "bInitiallyOpen", "OpenAnimationRate", "CloseAnimationRate",
        "DelayBeforeOpening", "StayOpenDuration",
    };
    // DamageResistanceSetName, UseVerbText and OverlayMaterial are deliberately NOT in the set
    // above: they're decoded only for DoorSwitch (see the DoorSwitch method below), but dozens of
    // unrelated classes -- pickups, furniture, other switches -- also carry them, undecoded. Adding
    // them here would mark those other classes' copies "interpreted" when nothing reads their value.

    /// <summary>Whether a property already has a typed representation in <see cref="LevelActor"/>.</summary>
    public static bool IsInterpretedProperty(string property) => Interpreted.Contains(property);

    public static LevelContext Analyze(string packageFile, IProgress<string>? progress = null)
    {
        using var package = BioShockPackage.Open(packageFile);
        return Analyze(package, progress);
    }

    public static LevelContext Analyze(BioShockPackage package, IProgress<string>? progress = null)
    {
        var defaults = new ClassDefaults(package);
        var actors = new List<LevelActor>();
        var failed = new List<SourceId>();
        var uninterpreted = new Dictionary<string, int>(StringComparer.Ordinal);
        string packageName = Path.GetFileNameWithoutExtension(package.FilePath);

        for (int i = 0; i < package.Exports.Count; i++)
        {
            var export = package.Exports[i];
            if (export.SerialSize < 64) continue;

            byte[] data;
            try { data = package.ReadExportData(export); }
            catch { continue; }

            var payload = ActorPayloadReader.TryRead(package, export, data);
            if (payload is null) continue;

            var source = new SourceId(packageName, export.Index, payload.ClassName, export.ObjectName);
            if (payload.Truncated)
            {
                failed.Add(source);
                continue;
            }

            actors.Add(BuildActor(package, defaults, source, payload, uninterpreted));

            if (progress is not null && actors.Count % 1000 == 0)
                progress.Report($"{actors.Count} actors");
        }

        ResolveMoverTriggers(actors);

        return Summarise(package, packageName, actors, failed, uninterpreted);
    }

    /// <summary>
    /// Second pass over the whole package: resolves every mover's <c>TriggeredBy</c> names against
    /// every other actor's <c>Label</c>, in place. Has to run after every actor in the package is
    /// built, unlike every other field on <see cref="LevelActor"/>, which is decoded from that one
    /// actor's own bytes — this is the one piece of "interaction metadata" that needs the whole
    /// package's Labels to resolve at all. See docs/research/interaction.md §2 for why <c>Label</c>
    /// and not <c>Tag</c>, and why an ambiguous name is left unresolved rather than guessed at.
    /// </summary>
    private static void ResolveMoverTriggers(List<LevelActor> actors)
    {
        var byLabel = new Dictionary<string, LevelActor>(StringComparer.Ordinal);
        var ambiguous = new HashSet<string>(StringComparer.Ordinal);
        foreach (var actor in actors)
        {
            if (actor.Label is not { } label) continue;
            if (!byLabel.TryAdd(label, actor)) ambiguous.Add(label);
        }

        for (int i = 0; i < actors.Count; i++)
        {
            var actor = actors[i];
            if (actor.Mover?.TriggeredBy is not { } raw
                || raw.Equals("none", StringComparison.OrdinalIgnoreCase))
                continue;

            var targets = new List<MoverTriggerTarget>();
            foreach (string rawName in raw.Split(','))
            {
                string name = rawName.Trim();
                if (name.Length == 0) continue;

                if (!ambiguous.Contains(name) && byLabel.TryGetValue(name, out var target))
                {
                    targets.Add(new MoverTriggerTarget
                    {
                        Name = name,
                        Resolved = true,
                        TargetExportIndex = target.Source.ExportIndex,
                        TargetClassName = target.Source.ClassName,
                    });
                }
                else
                {
                    targets.Add(new MoverTriggerTarget { Name = name, Resolved = false });
                }
            }

            actors[i] = actor with { Mover = actor.Mover with { ResolvedTriggers = targets } };
        }
    }

    /// <summary>
    /// Reads <c>Region</c>, UE2's <c>FPointRegion</c>, as a nested tagged property list.
    /// </summary>
    /// <remarks>
    /// Every actor in the game carries one. Returns null rather than a partial region when the
    /// nested walk fails, so a caller cannot mistake a parse failure for zone 0.
    /// </remarks>
    private static ActorRegion? ReadRegion(BioShockPackage package, ActorPayload payload)
    {
        if (payload.Find("Region") is not { Value.Length: > 0 } region) return null;

        List<UnrealProperty> fields;
        try { fields = UnrealPropertyReader.Read(region.Value, package.Names, out _); }
        catch (Exception ex) when (ex is InvalidDataException or IndexOutOfRangeException
                                       or ArgumentOutOfRangeException)
        {
            return null;
        }

        var leaf = fields.FirstOrDefault(f => f.Name == "iLeaf");
        var zone = fields.FirstOrDefault(f => f.Name == "ZoneNumber");
        if (leaf is null || zone is null) return null;

        return new ActorRegion { Leaf = leaf.AsInt(), ZoneNumber = zone.AsByte() };
    }

    private static LevelActor BuildActor(
        BioShockPackage package, ClassDefaults defaults, SourceId source, ActorPayload payload,
        Dictionary<string, int> uninterpreted)
    {
        foreach (var property in payload.Properties)
            if (!Interpreted.Contains(property.Name))
                uninterpreted[property.Name] = uninterpreted.GetValueOrDefault(property.Name) + 1;

        return new LevelActor
        {
            Source = source,
            Label = ReadName(package, payload, "Label"),
            Tag = ReadName(package, payload, "Tag"),
            Region = ReadRegion(package, payload),
            RegionActor = RegionActor(package, source.ClassName, payload),
            TrainingConcepts = NameArray(package, payload, "Concepts"),
            Spawner = Spawner(package, source.ClassName, payload),
            Cubemap = Reference(package, defaults, payload, "Cubemap", "Cubemap"),
            Projector = Projector(package, defaults, source.ClassName, payload),
            HavokForce = HavokForce(package, defaults, source.ClassName, payload),
            LootSlot = Reference(package, defaults, payload, "LootSlot", null),
            HavokConstraint = HavokConstraint(package, defaults, source.ClassName, payload),
            AntiPortal = Reference(package, defaults, payload, "AntiPortal", null),
            MapUiMarker = MapUiMarker(package, source.ClassName, payload),
            Vending = Vending(package, defaults, source.ClassName, payload),
            Interaction = Interaction(package, source.ClassName, payload),
            LevelInfo = LevelInfo(package, defaults, source.ClassName, payload),
            ShockAiScout = ShockAiScout(package, defaults, source.ClassName, payload),
            Mover = Mover(package, source.ClassName, payload),
            Door = Door(package, defaults, payload),
            DoorSwitch = DoorSwitch(package, defaults, source.ClassName, payload),
            Transform = ReadTransform(payload),
            StaticMesh = Reference(package, defaults, payload, "StaticMesh", "StaticMesh"),
            SkeletalMesh = Reference(package, defaults, payload, "Mesh", "SkeletalMesh")
                           ?? Reference(package, defaults, payload, "SkeletalMesh", "SkeletalMesh"),
            Brush = Reference(package, defaults, payload, "Brush", "Model"),
            Attachment = Reference(package, defaults, payload, "Base", null)
                         ?? Reference(package, defaults, payload, "Owner", null),
            Navigation = Navigation(package, payload),
            ScriptActions = ScriptActions(package, payload),
            Emitters = Emitters(package, payload),
            MaterialOverrides = ReferenceArray(package, payload, "Skins"),
            Groups = ReferenceArray(package, payload, "OwnerGroups").Select(r => r.ObjectName).ToList(),
            Properties = payload.Properties,
            Truncated = payload.Truncated,
            Trailer = payload.Trailer,
            UnknownHeaderField = payload.UnknownHeaderField,
        };
    }

    /// <summary>
    /// Reads the transform properties. Each is optional and each absence means the engine default,
    /// so which ones were present is recorded rather than inferred back from the values.
    /// </summary>
    public static ActorTransform ReadTransform(ActorPayload payload)
    {
        var present = new List<string>();
        var transform = ActorTransform.Default;

        if (payload.Find("Location") is { } location && PropertyValues.AsVector(location) is { } l)
        {
            transform = transform with { Location = l };
            present.Add("Location");
        }
        if (payload.Find("Rotation") is { } rotation && PropertyValues.AsRotator(rotation) is { } r)
        {
            transform = transform with { Rotation = r };
            present.Add("Rotation");
        }
        if (payload.Find("DrawScale") is { } drawScale && drawScale.Value.Length >= 4)
        {
            transform = transform with { DrawScale = drawScale.AsFloat() };
            present.Add("DrawScale");
        }
        if (payload.Find("DrawScale3D") is { } drawScale3D && PropertyValues.AsVector(drawScale3D) is { } s)
        {
            transform = transform with { DrawScale3D = s };
            present.Add("DrawScale3D");
        }
        if (payload.Find("PrePivot") is { } prePivot && PropertyValues.AsVector(prePivot) is { } p)
        {
            transform = transform with { PrePivot = p };
            present.Add("PrePivot");
        }

        return transform with { Present = present };
    }

    private static string? ReadName(BioShockPackage package, ActorPayload payload, string property) =>
        payload.Find(property) is { } found ? PropertyValues.AsName(found, package) : null;

    private static IReadOnlyList<string> NameArray(BioShockPackage package, ActorPayload payload, string property) =>
        payload.Find(property) is { Type: UnrealPropertyType.Array } found
        && PropertyValues.TryAsNameIndexArrayExact(found, package, out var values) ? values : [];

    private static SpawnerActorData? Spawner(BioShockPackage package, string className, ActorPayload payload)
    {
        if (!className.EndsWith("Spawner", StringComparison.Ordinal)) return null;
        string[] aiArrayNames = ["GlobalAITypes", "InitialAITypes", "RepopulationAITypes"];
        if (!aiArrayNames.Any(name => payload.Find(name) is not null)
            && payload.Find("OverriddenAIArchetypeNames") is null
            && payload.Find("SpawnZones") is null) return null;

        bool complete = true;
        IReadOnlyList<string> IndexNames(string name)
        {
            if (payload.Find(name) is not { Type: UnrealPropertyType.Array } property) return [];
            if (PropertyValues.TryAsNameIndexArrayExact(property, package, out var values)) return values;
            complete = false;
            return [];
        }
        IReadOnlyList<string> NumberedNames(string name)
        {
            if (payload.Find(name) is not { Type: UnrealPropertyType.Array } property) return [];
            if (PropertyValues.TryAsNameArrayExact(property, package, out var values)) return values;
            complete = false;
            return [];
        }

        return new SpawnerActorData
        {
            GlobalPatrol = ReadName(package, payload, "GlobalPatrol"),
            InitialPatrol = ReadName(package, payload, "InitialPatrol"),
            RepopulationPatrol = ReadName(package, payload, "RepopulationPatrol"),
            InitialLabel = ReadName(package, payload, "InitialLabel"),
            GlobalAiTypes = IndexNames("GlobalAITypes"),
            InitialAiTypes = IndexNames("InitialAITypes"),
            RepopulationAiTypes = IndexNames("RepopulationAITypes"),
            OverriddenAiArchetypeNames = NumberedNames("OverriddenAIArchetypeNames"),
            SpawnZones = NumberedNames("SpawnZones"),
            Complete = complete,
        };
    }

    private static ProjectorActorData? Projector(
        BioShockPackage package, ClassDefaults defaults, string className, ActorPayload payload)
    {
        if (className is not ("GoreLight_Decal" or "Caustic_Projector" or "Projector")) return null;
        bool complete = true;
        int? Int(string name) => payload.Find(name) is { Type: UnrealPropertyType.Int } value
            && value.Value.Length == 4 ? BinaryPrimitives.ReadInt32LittleEndian(value.Value) : null;
        float? Float(string name) => payload.Find(name) is { Type: UnrealPropertyType.Float } value
            && value.Value.Length == 4 ? BinaryPrimitives.ReadSingleLittleEndian(value.Value) : null;
        bool? Bool(string name) => payload.Find(name) is { Type: UnrealPropertyType.Bool } value
            ? value.BoolValue : null;
        Vector3? tile = payload.Find("Tile") is { Type: UnrealPropertyType.Struct, StructName: "Vector" } tileProperty
            ? PropertyValues.AsVector(tileProperty) : null;
        PropertyValues.ProjectorGradient? gradient = null;
        if (payload.Find("AngleGradient") is { Type: UnrealPropertyType.Struct, StructName: "ProjectorGradient" } angle)
        {
            if (PropertyValues.TryAsProjectorGradientExact(angle, package, out var decoded)) gradient = decoded;
            else complete = false;
        }
        return new ProjectorActorData
        {
            Material = Reference(package, defaults, payload, "Material", null),
            Tile = tile,
            MaxTraceDistance = Int("MaxTraceDistance"),
            ZBiasOverride = Int("ZBiasOverride"),
            ScaleInTime = Float("ScaleInTime"),
            AngleGradient = gradient,
            ProjectOnBackfaces = Bool("bProjectOnBackfaces"),
            ProjectStaticMesh = Bool("bProjectStaticMesh"),
            ProjectSkeletalMesh = Bool("bProjectSkeletalMesh"),
            ShouldBeAttached = Bool("bShouldBeAttached"),
            Complete = complete,
        };
    }

    private static HavokForceActorData? HavokForce(
        BioShockPackage package, ClassDefaults defaults, string className, ActorPayload payload)
    {
        if (className != "HavokForceActor") return null;
        var forceType = Reference(package, defaults, payload, "ForceType", null);
        var forceShape = Reference(package, defaults, payload, "ForceShape", null);
        if (forceType is null || forceShape is null) return null;
        return new HavokForceActorData
        {
            ForceType = forceType,
            ForceShape = forceShape,
            ForceFilter = Reference(package, defaults, payload, "ForceFilter", null),
        };
    }

    private static HavokConstraintActorData? HavokConstraint(
        BioShockPackage package, ClassDefaults defaults, string className, ActorPayload payload)
    {
        if (className is not ("HavokHingeConstraint" or "HavokBSConstraint")) return null;
        var actorA = Reference(package, defaults, payload, "hkAttachedActorA", null);
        if (actorA is null) return null;
        bool? Bool(string name) => payload.Find(name) is { Type: UnrealPropertyType.Bool } value
            ? value.BoolValue : null;
        float? Float(string name) => payload.Find(name) is { Type: UnrealPropertyType.Float, Value.Length: 4 } value
            ? BinaryPrimitives.ReadSingleLittleEndian(value.Value) : null;
        return new HavokConstraintActorData
        {
            AttachedActorA = actorA,
            AttachedActorB = Reference(package, defaults, payload, "hkAttachedActorB", null),
            DisableCollisions = Bool("bDisableCollisions"),
            UseLimitedHinge = Bool("hkUseLimitedHinge"),
            LimitedHingeFrictionValue = Float("hkLimitedHingeFrictionValue"),
            LimitedHingeTauFactor = Float("hkLimitedHingeTauFactor"),
        };
    }

    private static MapUiMarkerData? MapUiMarker(
        BioShockPackage package, string className, ActorPayload payload)
    {
        if (className != "MapUILayerMarker") return null;
        string? layer = ReadName(package, payload, "LayerName");
        string? scale = ReadName(package, payload, "ScaleMarkerName");
        IReadOnlyList<string> regions = [];
        bool complete = payload.Find("RegionNames") is { Type: UnrealPropertyType.Array } property
                        && PropertyValues.TryAsNameArrayExact(property, package, out regions);
        if (layer is null || scale is null) complete = false;
        return new MapUiMarkerData
        {
            LayerName = layer ?? string.Empty,
            ScaleMarkerName = scale ?? string.Empty,
            RegionNames = complete ? regions : [],
            Complete = complete,
        };
    }

    private static VendingActorData? Vending(
        BioShockPackage package, ClassDefaults defaults, string className, ActorPayload payload)
    {
        if (className != "PlaceableVendingStation") return null;
        string? tableName = ReadName(package, payload, "VendingTableName");
        string? hackInfo = ReadName(package, payload, "HackInfoName");
        var table = Reference(package, defaults, payload, "VendingTable", null);
        var meshInstance = Reference(package, defaults, payload, "StaticMeshInstance", null);
        if (tableName is null || hackInfo is null || table is null || meshInstance is null) return null;
        int? notification = payload.Find("SendDestructionNotification") is
            { Type: UnrealPropertyType.Int, Value.Length: 4 } value
            ? BinaryPrimitives.ReadInt32LittleEndian(value.Value) : null;
        bool? canBeHacked = payload.Find("bCanBeHacked") is { Type: UnrealPropertyType.Bool } hack
            ? hack.BoolValue : null;
        return new VendingActorData
        {
            VendingTableName = tableName,
            VendingTable = table,
            HackInfoName = hackInfo,
            StaticMeshInstance = meshInstance,
            DestructionNotification = notification,
            CanBeHacked = canBeHacked,
        };
    }

    private static InteractionActorData? Interaction(
        BioShockPackage package, string className, ActorPayload payload)
    {
        if (className is not ("DoorKeypadControl" or "dyn_toolbox_open")) return null;
        bool? Bool(string name) => payload.Find(name) is { Type: UnrealPropertyType.Bool } value
            ? value.BoolValue : null;
        return new InteractionActorData
        {
            DoorLabel = ReadName(package, payload, "DoorLabel"),
            HackInfoName = ReadName(package, payload, "HackInfoName"),
            Hackable = Bool("bHackable"),
            ShowHudElements = Bool("bShowHudElements"),
        };
    }

    private static LevelInfoActorData? LevelInfo(
        BioShockPackage package, ClassDefaults defaults, string className, ActorPayload payload)
    {
        if (className != "LevelInfo") return null;
        bool complete = true;
        float? Float(string name) => payload.Find(name) is { Type: UnrealPropertyType.Float, Value.Length: 4 } value
            ? BinaryPrimitives.ReadSingleLittleEndian(value.Value) : null;
        Vector3? Vector(string name) => payload.Find(name) is
            { Type: UnrealPropertyType.Struct, StructName: "Vector" } value ? PropertyValues.AsVector(value) : null;
        UnrealRotator? Rotator(string name) => payload.Find(name) is
            { Type: UnrealPropertyType.Struct, StructName: "Rotator" } value ? PropertyValues.AsRotator(value) : null;

        IReadOnlyList<IReadOnlyList<UnrealProperty>> Structs(string name)
        {
            if (payload.Find(name) is { Type: UnrealPropertyType.Array } property
                && PropertyValues.TryAsStructArrayExact(property, package, out var values)) return values;
            complete = false;
            return [];
        }
        string? FieldName(IReadOnlyList<UnrealProperty> fields, string name) =>
            fields.FirstOrDefault(field => field.Name == name) is { Type: UnrealPropertyType.Name } value
                ? PropertyValues.AsName(value, package) : null;
        string? FieldString(IReadOnlyList<UnrealProperty> fields, string name) =>
            fields.FirstOrDefault(field => field.Name == name) is { Type: UnrealPropertyType.Str } value
                ? PropertyValues.AsString(value) : null;
        float? FieldFloat(IReadOnlyList<UnrealProperty> fields, string name) =>
            fields.FirstOrDefault(field => field.Name == name) is { Type: UnrealPropertyType.Float, Value.Length: 4 } value
                ? BinaryPrimitives.ReadSingleLittleEndian(value.Value) : null;
        bool? FieldBool(IReadOnlyList<UnrealProperty> fields, string name) =>
            fields.FirstOrDefault(field => field.Name == name) is { Type: UnrealPropertyType.Bool } value
                ? value.BoolValue : null;

        var navigationPoints = new List<AssetReference>();
        if (payload.Find("NavigationPointList") is { Type: UnrealPropertyType.Array } navigationProperty
            && PropertyValues.TryAsReferenceArrayExact(navigationProperty, out var navigationIndices))
        {
            foreach (var index in navigationIndices)
            {
                if (Describe(package, index, "actor", null) is { } reference) navigationPoints.Add(reference);
                else complete = false;
            }
        }
        else complete = false;

        var pressureRegions = Structs("PressureRegions").Select(fields =>
        {
            string? name = FieldName(fields, "PressureRegion");
            byte? pressure = fields.FirstOrDefault(field => field.Name == "Pressure") is
                { Type: UnrealPropertyType.Byte, Value.Length: > 0 } value ? value.Value[0] : null;
            float? duration = FieldFloat(fields, "EffectsDuration");
            if (name is null || pressure is null || duration is null) complete = false;
            return new PressureRegionData(name ?? string.Empty, pressure ?? 0, duration ?? 0);
        }).ToList();
        var mapUiRegions = Structs("MapUIRegions").Select(fields =>
        {
            string? map = FieldName(fields, "MapUIRegion");
            string? hud = FieldName(fields, "HUDRegion");
            float? visited = FieldFloat(fields, "TimeLastVisited");
            if (map is null || hud is null || visited is null) complete = false;
            return new MapUiRegionData(map ?? string.Empty, hud ?? string.Empty,
                FieldBool(fields, "Revealed"), visited ?? 0);
        }).ToList();
        var mapHudRegions = Structs("MapHUDRegions").Select(fields =>
        {
            string? hud = FieldName(fields, "HUDRegion");
            string? description = FieldString(fields, "Description");
            if (hud is null || description is null) complete = false;
            return new MapHudRegionData(hud ?? string.Empty, description ?? string.Empty);
        }).ToList();
        var animationGroups = Structs("RequiredAnimationGroups").Select(fields =>
        {
            string? packageName = FieldName(fields, "AnimPackageName");
            string? groupName = FieldName(fields, "AnimGroupName");
            if (packageName is null || groupName is null) complete = false;
            return new RequiredAnimationGroupData(packageName ?? string.Empty, groupName ?? string.Empty);
        }).ToList();

        return new LevelInfoActorData
        {
            TimeSeconds = Float("TimeSeconds"),
            Title = payload.Find("Title") is { Type: UnrealPropertyType.Str } title ? PropertyValues.AsString(title) : null,
            FictionalMapName = payload.Find("LabelFictionalMapName") is { Type: UnrealPropertyType.Str } fictional
                ? PropertyValues.AsString(fictional) : null,
            Summary = Reference(package, defaults, payload, "Summary", null),
            SpawningManager = Reference(package, defaults, payload, "SpawningManager", null),
            GlowSettings = Reference(package, defaults, payload, "GlowSettings", null),
            ToneMapSettings = Reference(package, defaults, payload, "ToneMapSettings", null),
            LevelAnimInfo = Reference(package, defaults, payload, "LevelAnimInfo", null),
            HasPathNodes = payload.Find("bHasPathNodes") is { Type: UnrealPropertyType.Bool } paths ? paths.BoolValue : null,
            CameraLocationDynamic = Vector("CameraLocationDynamic"),
            CameraLocationTop = Vector("CameraLocationTop"),
            CameraLocationFront = Vector("CameraLocationFront"),
            CameraLocationSide = Vector("CameraLocationSide"),
            CameraRotationDynamic = Rotator("CameraRotationDynamic"),
            NavigationPoints = navigationPoints,
            PressureRegions = pressureRegions,
            MapUiRegions = mapUiRegions,
            MapHudRegions = mapHudRegions,
            RequiredAnimationGroups = animationGroups,
            AmbientXGroundRatio = Float("CurrentAmbientXGroundRatio"),
            AmbientColorHighMultiplier = Float("CurrentAmbientColorHighMultiplier"),
            AmbientColorLowMultiplier = Float("CurrentAmbientColorLowMultiplier"),
            AmbientContrastPower = Float("CurrentAmbientContrastPower"),
            Complete = complete,
        };
    }

    private static ShockAiScoutData? ShockAiScout(
        BioShockPackage package, ClassDefaults defaults, string className, ActorPayload payload)
    {
        if (className != "ShockAIScout") return null;
        bool complete = true;
        float? Float(string name) => payload.Find(name) is { Type: UnrealPropertyType.Float, Value.Length: 4 } value
            ? BinaryPrimitives.ReadSingleLittleEndian(value.Value) : null;
        Vector3? Vector(string name) => payload.Find(name) is
            { Type: UnrealPropertyType.Struct, StructName: "Vector" } value ? PropertyValues.AsVector(value) : null;
        bool? Bool(string name) => payload.Find(name) is { Type: UnrealPropertyType.Bool } value
            ? value.BoolValue : null;
        IReadOnlyList<int> points = [];
        if (payload.Find("PointCollection") is { Type: UnrealPropertyType.Array } pointProperty
            && PropertyValues.TryAsReferenceArrayExact(pointProperty, out var pointIndices))
            points = pointIndices.Select(index => index.Value).ToList();
        else complete = false;
        int? notification = payload.Find("SendDestructionNotification") is
            { Type: UnrealPropertyType.Int, Value.Length: 4 } notify
            ? BinaryPrimitives.ReadInt32LittleEndian(notify.Value) : null;
        var controller = Reference(package, defaults, payload, "Controller", null);
        var headVolume = Reference(package, defaults, payload, "HeadVolume", null);
        if (controller?.Status == ResolutionStatus.Failed || headVolume?.Status == ResolutionStatus.Failed) complete = false;
        return new ShockAiScoutData
        {
            PointCollectionReferences = points,
            LastPathfindingOrigin = Vector("LastPathfindingOrigin"),
            LastPathfindingLocation = Vector("LastPathfindingLocation"),
            LastPathfindingTime = Float("LastPathfindingTime"),
            LastPathfindingFailedTime = Float("LastPathfindingFailedTime"),
            LastPathfindingResult = Float("LastPathfindingResult"),
            Controller = controller,
            JumpCapable = Bool("bJumpCapable"),
            CanFly = Bool("bCanFly"),
            CanUseCeiling = Bool("bCanUseCeiling"),
            LastValidAnchorTime = Float("LastValidAnchorTime"),
            Floor = Vector("Floor"),
            HeadVolume = headVolume,
            CollisionRadius = Float("CollisionRadius"),
            CollisionHeight = Float("CollisionHeight"),
            DestructionNotification = notification,
            Complete = complete,
        };
    }

    private static NavigationActorData? Navigation(BioShockPackage package, ActorPayload payload)
    {
        var pathList = ReferenceArray(package, payload, "PathList");
        var autoGenerated = ReferenceArray(package, payload, "AutoGeneratedFlyingPathNodes");
        float? radius = payload.Find("PathCollisionRadius") is { Type: UnrealPropertyType.Float } collision
            && collision.Value.Length >= 4
            ? collision.AsFloat()
            : null;
        bool flagPresent = payload.Find("bIsAutoGenerated") is { Type: UnrealPropertyType.Bool };

        return pathList.Count > 0 || autoGenerated.Count > 0 || radius is not null || flagPresent
            ? new NavigationActorData
            {
                PathLinks = pathList,
                AutoGeneratedFlyingPathNodes = autoGenerated,
                PathCollisionRadius = radius,
                AutoGeneratedFlagSerialized = flagPresent,
            }
            : null;
    }

    private static RegionActorData? RegionActor(
        BioShockPackage package, string className, ActorPayload payload)
    {
        if (!className.EndsWith("Volume", StringComparison.Ordinal)
            && !className.Contains("Trigger", StringComparison.Ordinal)
            && !className.Contains("Zone", StringComparison.Ordinal))
            return null;

        bool? Bool(string name) => payload.Find(name) is { Type: UnrealPropertyType.Bool } value
            ? value.BoolValue
            : null;
        float? Float(string name) => payload.Find(name) is { Type: UnrealPropertyType.Float, Value.Length: >= 4 } value
            ? value.AsFloat()
            : null;
        Vector3? Vector(string name) => payload.Find(name) is { Type: UnrealPropertyType.Struct, StructName: "Vector" } value
            ? PropertyValues.AsVector(value)
            : null;
        LightColor? Color(string name) => payload.Find(name) is { Type: UnrealPropertyType.Struct, StructName: "Color" } value
            ? PropertyValues.AsColor(value)
            : null;
        string? Name(string name) => payload.Find(name) is { Type: UnrealPropertyType.Name } value
            ? PropertyValues.AsName(value, package)
            : null;

        bool complete = true;
        IReadOnlyList<string> Names(string name)
        {
            if (payload.Find(name) is not { Type: UnrealPropertyType.Array } property) return [];
            if (PropertyValues.TryAsNameArrayExact(property, package, out var names)) return names;
            complete = false;
            return [];
        }

        IReadOnlyList<AssetReference> References(string name)
        {
            if (payload.Find(name) is not { Type: UnrealPropertyType.Array } property) return [];
            if (!PropertyValues.TryAsReferenceArrayExact(property, out var indices))
            {
                complete = false;
                return [];
            }
            var result = new List<AssetReference>(indices.Count);
            foreach (var index in indices)
            {
                if (index.IsNull || Describe(package, index, "actor", null) is not { } reference)
                {
                    complete = false;
                    continue;
                }
                result.Add(reference);
            }
            return result;
        }

        var classReferences = new List<AssetReference>();
        if (payload.Find("TriggerOnlyByClass") is { Type: UnrealPropertyType.Array } classes)
        {
            if (!PropertyValues.TryAsReferenceArrayExact(classes, out var indices)) complete = false;
            else
            {
                foreach (var index in indices)
                {
                    if (index.IsNull || Describe(package, index, "actor", null) is not { } reference)
                    {
                        complete = false;
                        continue;
                    }
                    classReferences.Add(reference);
                }
            }
        }

        string? triggeredBy = payload.Find("TriggeredBy") is { Type: UnrealPropertyType.Str } text
            ? PropertyValues.AsString(text)
            : null;
        if (payload.Find("TriggeredBy") is not null && triggeredBy is null) complete = false;

        ZoneAmbientData? Ambient(string prefix)
        {
            var result = new ZoneAmbientData
            {
                VectorHigh = Vector(prefix + "AmbientVectorHigh"),
                ColorHigh = Color(prefix + "AmbientColorHigh"),
                ColorHighMultiplier = Float(prefix + "AmbientColorHighMultiplier"),
                ColorLowMultiplier = Float(prefix + "AmbientColorLowMultiplier"),
                ContrastPower = Float(prefix + "AmbientContrastPower"),
                XGroundRatio = Float(prefix + "AmbientXGroundRatio"),
            };
            return result.VectorHigh is null && result.ColorHigh is null
                   && result.ColorHighMultiplier is null && result.ColorLowMultiplier is null
                   && result.ContrastPower is null && result.XGroundRatio is null ? null : result;
        }

        ZoneFogData? Fog(string enabledName, string clipName, string prefix)
        {
            var result = new ZoneFogData
            {
                Enabled = Bool(enabledName),
                Clip = Bool(clipName),
                Color = Color(prefix + "DistanceFogColor"),
                Start = Float(prefix + "DistanceFogStart"),
                End = Float(prefix + "DistanceFogEnd"),
                MaxContribution = Float(prefix + "MaxFogContribution"),
            };
            return result.Enabled is null && result.Clip is null && result.Color is null
                   && result.Start is null && result.End is null && result.MaxContribution is null ? null : result;
        }

        ZoneActorData? zone = null;
        if (className.Contains("Zone", StringComparison.Ordinal))
        {
            zone = new ZoneActorData
            {
                CurrentAmbient = Ambient("Current"),
                NormalPressureAmbient = Ambient("NormalPressure"),
                HighPressureAmbient = Ambient("HighPressure"),
                LowPressureAmbient = Ambient("LowPressure"),
                CurrentFog = Fog("bDistanceFog", "bDistanceFogClip", string.Empty),
                NormalFog = Fog("NormalEnableDistanceFog", string.Empty, "Normal"),
                HighFog = Fog("HighEnableDistanceFog", string.Empty, "High"),
                ReverbType = payload.Find("ReverbType") is { Type: UnrealPropertyType.Byte } reverb
                    ? reverb.AsByte()
                    : null,
                MapUiRegion = Name("MapUIRegion"),
                PressureRegion = Name("PressureRegion"),
                PressureEffectsDuration = Float("PressureEffectsDuration"),
                TimeLastPressureChange = Float("TimeLastPressureChange"),
                SpawnZones = Names("SpawnZones"),
                EffectsContexts = Names("EffectsContexts"),
                ManualExcludes = References("ManualExcludes"),
            };
        }

        ActorScaleData? Scale(string name)
        {
            if (payload.Find(name) is not { Type: UnrealPropertyType.Struct, StructName: "Scale" } property)
                return null;
            try
            {
                var fields = UnrealPropertyReader.Read(property.Value, package.Names, out int end, out bool truncated, 0);
                var scale = fields.FirstOrDefault(field => field.Name == "Scale"
                                                            && field.Type == UnrealPropertyType.Struct
                                                            && field.StructName == "Vector");
                var sheerRate = fields.FirstOrDefault(field => field.Name == "SheerRate"
                                                                && field.Type == UnrealPropertyType.Float);
                var sheerAxis = fields.FirstOrDefault(field => field.Name == "SheerAxis"
                                                                && field.Type == UnrealPropertyType.Byte);
                if (truncated || end != property.Value.Length || scale is null || sheerRate is null || sheerAxis is null
                    || PropertyValues.AsVector(scale) is not { } vector)
                {
                    complete = false;
                    return null;
                }
                return new ActorScaleData
                {
                    Scale = vector,
                    SheerRate = sheerRate.AsFloat(),
                    SheerAxis = sheerAxis.AsByte(),
                };
            }
            catch (Exception ex) when (ex is InvalidDataException or IndexOutOfRangeException
                                           or ArgumentOutOfRangeException)
            {
                complete = false;
                return null;
            }
        }

        AssetReference? waterMesh = null;
        if (payload.Find("WaterMesh1") is { Type: UnrealPropertyType.Object } water
            && PropertyValues.AsReference(water) is { } waterIndex && !waterIndex.IsNull)
        {
            waterMesh = Describe(package, waterIndex, "actor", null);
            if (waterMesh is null) complete = false;
        }

        return new RegionActorData
        {
            MainScale = Scale("MainScale"),
            PostScale = Scale("PostScale"),
            BlockActors = Bool("bBlockActors"),
            BlockHavok = Bool("bBlockHavok"),
            BlockNonZeroExtentTraces = Bool("bBlockNonZeroExtentTraces"),
            BlockPlayers = Bool("bBlockPlayers"),
            BlockZeroExtentTraces = Bool("bBlockZeroExtentTraces"),
            CollideActors = Bool("bCollideActors"),
            Disabled = Bool("Disabled"),
            Enabled = Bool("enabled") ?? Bool("bEnabled"),
            TriggerOnlyOnce = Bool("TriggerOnlyOnce"),
            TriggerWhenNotSeen = Bool("TriggerWhenNotSeen"),
            CollisionRadius = Float("CollisionRadius"),
            CollisionHeight = Float("CollisionHeight"),
            MinimumDistance = Float("MinimumDistance"),
            TriggeredBy = triggeredBy,
            TriggerOnlyByLabels = Names("TriggerOnlyByLabel"),
            TriggeredByFilter = Names("triggeredByFilter"),
            TriggerOnlyByClasses = classReferences,
            WaterMesh = waterMesh,
            WaterAxis = payload.Find("Axis") is { Type: UnrealPropertyType.Byte } axis ? axis.AsByte() : null,
            MovingInWaterPenalty = Float("MovingInWaterPenalty"),
            Priority = payload.Find("Priority") is { Type: UnrealPropertyType.Int } priority ? priority.AsInt() : null,
            NoDelete = Bool("bNoDelete"),
            Zone = zone,
            Complete = complete,
        };
    }

    /// <summary>
    /// The typed subset of a <c>Mover</c>/<c>ScriptableMover</c> — what triggers it and its start
    /// pose, not its keyframe path (see <see cref="MoverActorData"/>). Gated on the exact class
    /// names rather than a substring match: <c>Int_FireMover</c> shares the "Mover" name but not
    /// the shape (no <c>BasePos</c>/<c>TriggeredBy</c> at all, confirmed by census), so a substring
    /// gate would silently attach an empty record to an unrelated class.
    /// </summary>
    private static MoverActorData? Mover(BioShockPackage package, string className, ActorPayload payload)
    {
        if (className is not ("Mover" or "ScriptableMover")) return null;

        bool complete = true;

        string? Name(string name)
        {
            if (payload.Find(name) is not { Type: UnrealPropertyType.Name } value) return null;
            var result = PropertyValues.AsName(value, package);
            if (result is null) complete = false;
            return result;
        }

        string? triggeredBy = null;
        if (payload.Find("TriggeredBy") is { } triggeredByProperty)
        {
            if (triggeredByProperty.Type == UnrealPropertyType.Str)
                triggeredBy = PropertyValues.AsString(triggeredByProperty);
            if (triggeredBy is null) complete = false;
        }

        return new MoverActorData
        {
            InitialState = Name("InitialState"),
            TriggeredBy = triggeredBy,
            BasePos = payload.Find("BasePos") is { Type: UnrealPropertyType.Struct, StructName: "Vector" } basePos
                ? PropertyValues.AsVector(basePos)
                : null,
            BaseRot = payload.Find("BaseRot") is { Type: UnrealPropertyType.Struct, StructName: "Rotator" } baseRot
                ? PropertyValues.AsRotator(baseRot)
                : null,
            MoveTime = payload.Find("MoveTime") is { Type: UnrealPropertyType.Float } moveTime
                ? moveTime.AsFloat()
                : null,
            StayOpenTime = payload.Find("StayOpenTime") is { Type: UnrealPropertyType.Float } stayOpenTime
                ? stayOpenTime.AsFloat()
                : null,
            UseTriggered = payload.Find("bUseTriggered") is { Type: UnrealPropertyType.Bool } useTriggered
                ? useTriggered.BoolValue
                : null,
            TriggerOnceOnly = payload.Find("bTriggerOnceOnly") is { Type: UnrealPropertyType.Bool } triggerOnceOnly
                ? triggerOnceOnly.BoolValue
                : null,
            MoverEncroachType = payload.Find("MoverEncroachType") is { Type: UnrealPropertyType.Byte } encroach
                ? encroach.AsByte()
                : null,
            MoverGlideType = payload.Find("MoverGlideType") is { Type: UnrealPropertyType.Byte } glide
                ? glide.AsByte()
                : null,
            Complete = complete,
        };
    }

    /// <summary>
    /// Typed door-state fields, gated on field presence rather than class name — see
    /// <see cref="DoorActorData"/>.
    /// </summary>
    private static DoorActorData? Door(BioShockPackage package, ClassDefaults defaults, ActorPayload payload)
    {
        bool? Bool(string name) => payload.Find(name) is { Type: UnrealPropertyType.Bool } value
            ? value.BoolValue
            : null;
        float? Float(string name) => payload.Find(name) is { Type: UnrealPropertyType.Float } value
            ? value.AsFloat()
            : null;

        var portal = Reference(package, defaults, payload, "DoorPortal", null);
        bool? locked = Bool("bLocked");
        bool? initiallyOpen = Bool("bInitiallyOpen");
        float? openRate = Float("OpenAnimationRate");
        float? closeRate = Float("CloseAnimationRate");
        float? delay = Float("DelayBeforeOpening");
        float? stayOpen = Float("StayOpenDuration");

        if (portal is null && locked is null && initiallyOpen is null && openRate is null
            && closeRate is null && delay is null && stayOpen is null)
            return null;

        return new DoorActorData
        {
            Portal = portal,
            Locked = locked,
            InitiallyOpen = initiallyOpen,
            OpenAnimationRate = openRate,
            CloseAnimationRate = closeRate,
            DelayBeforeOpening = delay,
            StayOpenDuration = stayOpen,
            Complete = true,
        };
    }

    /// <summary>
    /// A <c>DoorSwitch</c>'s interaction-verb fields. Gated on the exact class name, not field
    /// presence — unlike <see cref="Door"/>'s fields, <c>DamageResistanceSetName</c>,
    /// <c>UseVerbText</c> and <c>OverlayMaterial</c> turned out to be generic interaction/combat
    /// properties shared by dozens of unrelated classes (pickups, furniture, other switches), found
    /// only after a whole-game check — a field-presence gate here would have silently attached a
    /// <see cref="DoorSwitchActorData"/> to actors with nothing to do with doors.
    /// </summary>
    private static DoorSwitchActorData? DoorSwitch(BioShockPackage package, ClassDefaults defaults, string className, ActorPayload payload)
    {
        if (className != "DoorSwitch") return null;

        string? damageResistanceSetName = payload.Find("DamageResistanceSetName") is { Type: UnrealPropertyType.Name } drsn
            ? PropertyValues.AsName(drsn, package)
            : null;
        string? useVerbText = payload.Find("UseVerbText") is { Type: UnrealPropertyType.Str } uvt
            ? PropertyValues.AsString(uvt)
            : null;
        var overlayMaterial = Reference(package, defaults, payload, "OverlayMaterial", null);

        return new DoorSwitchActorData
        {
            DamageResistanceSetName = damageResistanceSetName,
            UseVerbText = useVerbText,
            OverlayMaterial = overlayMaterial,
            Complete = true,
        };
    }

    private static ScriptActorData? ScriptActions(BioShockPackage package, ActorPayload payload)
    {
        if (payload.Find("Actions") is not { Type: UnrealPropertyType.Array } actions) return null;
        if (!PropertyValues.TryAsReferenceArrayExact(actions, out var indices))
            return new ScriptActorData { Complete = false };

        var references = new List<AssetReference>(indices.Count);
        foreach (var index in indices)
        {
            if (index.IsNull || Describe(package, index, "actor", null) is not { } reference)
                return new ScriptActorData { Complete = false };
            references.Add(reference);
        }

        return new ScriptActorData { Actions = references, Complete = true };
    }

    private static EmitterActorData? Emitters(BioShockPackage package, ActorPayload payload)
    {
        if (payload.Find("Emitters") is not { Type: UnrealPropertyType.Array } emitters) return null;
        if (!PropertyValues.TryAsReferenceArrayExact(emitters, out var indices))
            return new EmitterActorData { Complete = false };

        var templates = new List<EmitterTemplateData>(indices.Count);
        foreach (var index in indices)
        {
            if (index.IsNull || Describe(package, index, "actor", null) is not { } reference)
                return new EmitterActorData { Complete = false };
            templates.Add(ReadEmitterTemplate(package, reference));
        }

        return new EmitterActorData { Templates = templates, Complete = true };
    }

    /// <summary>
    /// Reads a particle-emitter template off any export's own raw property list — a placed level
    /// actor's <c>Emitters</c> array entry (its original use here) or a weapon FX class's own
    /// <c>Emitters</c> array entry (<see cref="Assets.WeaponEffects"/>): both are the exact same
    /// shape, an <c>Emitter</c>-derived export's property list, so this reader doesn't care which.
    /// </summary>
    internal static EmitterTemplateData ReadEmitterTemplate(BioShockPackage package, AssetReference source)
    {
        if (source.Source is not { } local)
            return new EmitterTemplateData { Source = source, PropertiesComplete = false };

        List<UnrealProperty> properties;
        bool truncated;
        try
        {
            properties = UnrealPropertyReader.Read(package.ReadExportData(package.Exports[local.ExportIndex]),
                package.Names, out _, out truncated);
        }
        catch (Exception ex) when (ex is InvalidDataException or IndexOutOfRangeException
                                       or ArgumentOutOfRangeException)
        {
            return new EmitterTemplateData { Source = source, PropertiesComplete = false };
        }

        UnrealProperty? Find(string name, UnrealPropertyType type) =>
            properties.FirstOrDefault(property => property.Name == name && property.Type == type);

        AssetReference? material = Find("Material", UnrealPropertyType.Object) is { } materialProperty
            && PropertyValues.AsReference(materialProperty) is { } materialIndex
            ? Describe(package, materialIndex, "emitter template", null)
            : null;
        AssetReference? staticMesh = Find("StaticMesh", UnrealPropertyType.Object) is { } meshProperty
            && PropertyValues.AsReference(meshProperty) is { } meshIndex
            ? Describe(package, meshIndex, "emitter template", null)
            : null;

        int? MaybeInt(string name) => Find(name, UnrealPropertyType.Int)?.AsInt();
        float? MaybeFloat(string name) => Find(name, UnrealPropertyType.Float)?.AsFloat();
        bool? MaybeBool(string name) => Find(name, UnrealPropertyType.Bool)?.BoolValue;
        byte? MaybeByte(string name) => Find(name, UnrealPropertyType.Byte)?.AsByte();
        FloatRange? MaybeRange(string name) => Find(name, UnrealPropertyType.Struct) is { } rangeProperty
            ? ReadFloatRange(package, rangeProperty)
            : null;
        AxisRange? MaybeAxisRange(string name) => Find(name, UnrealPropertyType.Struct) is { } axisProperty
            ? ReadAxisRange(package, axisProperty)
            : null;
        Vector3? MaybeVector(string name) => Find(name, UnrealPropertyType.Struct) is { } vectorProperty
            ? PropertyValues.AsVector(vectorProperty)
            : null;
        IReadOnlyList<FloatCurveKey>? MaybeFloatCurve(string name, string valueField) =>
            Find(name, UnrealPropertyType.Array) is { } curveProperty
                ? ReadFloatCurve(package, curveProperty, valueField)
                : null;
        IReadOnlyList<ColorCurveKey>? MaybeColorCurve(string name) =>
            Find(name, UnrealPropertyType.Array) is { } curveProperty
                ? ReadColorCurve(package, curveProperty)
                : null;
        IReadOnlyList<VectorCurveKey>? MaybeVectorCurve(string name, string valueField) =>
            Find(name, UnrealPropertyType.Array) is { } curveProperty
                ? ReadVectorCurve(package, curveProperty, valueField)
                : null;

        return new EmitterTemplateData
        {
            Source = source,
            Material = material,
            MaxParticles = MaybeInt("MaxParticles"),
            ParticlesPerSecond = MaybeFloat("ParticlesPerSecond"),
            InitialParticlesPerSecond = MaybeFloat("InitialParticlesPerSecond"),
            AutomaticInitialSpawning = MaybeBool("AutomaticInitialSpawning"),
            RespawnDeadParticles = MaybeBool("RespawnDeadParticles"),
            LifetimeRange = MaybeRange("LifetimeRange"),
            StartSizeRange = MaybeAxisRange("StartSizeRange"),
            UniformSize = MaybeBool("UniformSize"),
            UseSizeScale = MaybeBool("UseSizeScale"),
            UseRegularSizeScale = MaybeBool("UseRegularSizeScale"),
            SizeScale = MaybeFloatCurve("SizeScale", "RelativeSize"),
            StartVelocityRange = MaybeAxisRange("StartVelocityRange"),
            Acceleration = MaybeVector("Acceleration"),
            VelocityScale = MaybeVectorCurve("VelocityScale", "RelativeVelocity"),
            StartLocationRange = MaybeAxisRange("StartLocationRange"),
            StartLocationOffset = MaybeVector("StartLocationOffset"),
            StartLocationShape = MaybeByte("StartLocationShape"),
            StartSpinRange = MaybeAxisRange("StartSpinRange"),
            SpinsPerSecondRange = MaybeAxisRange("SpinsPerSecondRange"),
            SpinParticles = MaybeBool("SpinParticles"),
            UseColorScale = MaybeBool("UseColorScale"),
            ColorScale = MaybeColorCurve("ColorScale"),
            Blending = MaybeByte("Blending"),
            CoordinateSystem = MaybeByte("CoordinateSystem"),
            TextureUSubdivisions = MaybeInt("TextureUSubdivisions"),
            TextureVSubdivisions = MaybeInt("TextureVSubdivisions"),
            StaticMesh = staticMesh,
            SegmentSizeScale = MaybeFloatCurve("SegmentSizeScale", "RelativeSize"),
            SegmentColorScale = MaybeColorCurve("SegmentColorScale"),
            PropertiesComplete = !truncated,
        };
    }

    /// <summary>
    /// An array of small tagged-property structs — a curve — read element by element rather than by
    /// a fixed stride: each element's own terminator reports where it ends, the same way the
    /// top-level property list does. Returns null unless the compact count and every element consume
    /// the array's complete value, so a curve whose shape doesn't match what's expected here yields
    /// nothing rather than a partial or misaligned read.
    /// </summary>
    /// <summary>Reads an <c>Array</c>-of-struct property's elements as their own field lists.
    /// Shared beyond this class by <see cref="Assets.WeaponEffects"/> for the same reason the
    /// curve readers below need it: a struct array is a struct array regardless of what property
    /// holds it.</summary>
    internal static IReadOnlyList<List<UnrealProperty>>? ReadStructArrayElements(
        BioShockPackage package, UnrealProperty property)
    {
        int offset = 0;
        int count;
        try { count = PropertyValues.ReadCompactIndex(property.Value, ref offset); }
        catch (Exception ex) when (ex is InvalidDataException or IndexOutOfRangeException
                                       or ArgumentOutOfRangeException)
        {
            return null;
        }
        if (count < 0) return null;

        var elements = new List<List<UnrealProperty>>(count);
        for (int i = 0; i < count; i++)
        {
            List<UnrealProperty> fields;
            bool truncated;
            try
            {
                fields = UnrealPropertyReader.Read(property.Value, package.Names, out int end, out truncated, start: offset);
                offset = end;
            }
            catch (Exception ex) when (ex is InvalidDataException or IndexOutOfRangeException
                                           or ArgumentOutOfRangeException)
            {
                return null;
            }
            if (truncated) return null;
            elements.Add(fields);
        }

        return offset == property.Value.Length ? elements : null;
    }

    private static IReadOnlyList<FloatCurveKey>? ReadFloatCurve(
        BioShockPackage package, UnrealProperty property, string valueField)
    {
        if (ReadStructArrayElements(package, property) is not { } elements) return null;

        var result = new List<FloatCurveKey>(elements.Count);
        foreach (var fields in elements)
        {
            var time = fields.FirstOrDefault(f => f.Name == "RelativeTime" && f.Type == UnrealPropertyType.Float);
            var value = fields.FirstOrDefault(f => f.Name == valueField && f.Type == UnrealPropertyType.Float);
            if (time is null || value is null) return null;
            result.Add(new FloatCurveKey(time.AsFloat(), value.AsFloat()));
        }
        return result;
    }

    private static IReadOnlyList<ColorCurveKey>? ReadColorCurve(BioShockPackage package, UnrealProperty property)
    {
        if (ReadStructArrayElements(package, property) is not { } elements) return null;

        var result = new List<ColorCurveKey>(elements.Count);
        foreach (var fields in elements)
        {
            var time = fields.FirstOrDefault(f => f.Name == "RelativeTime" && f.Type == UnrealPropertyType.Float);
            var color = fields.FirstOrDefault(f => f.Name == "Color" && f.Type == UnrealPropertyType.Struct);
            if (time is null || color is null || PropertyValues.AsColor(color) is not { } decoded) return null;
            result.Add(new ColorCurveKey(time.AsFloat(), decoded));
        }
        return result;
    }

    private static IReadOnlyList<VectorCurveKey>? ReadVectorCurve(
        BioShockPackage package, UnrealProperty property, string valueField)
    {
        if (ReadStructArrayElements(package, property) is not { } elements) return null;

        var result = new List<VectorCurveKey>(elements.Count);
        foreach (var fields in elements)
        {
            var time = fields.FirstOrDefault(f => f.Name == "RelativeTime" && f.Type == UnrealPropertyType.Float);
            var value = fields.FirstOrDefault(f => f.Name == valueField && f.Type == UnrealPropertyType.Struct);
            if (time is null || value is null || PropertyValues.AsVector(value) is not { } decoded) return null;
            result.Add(new VectorCurveKey(time.AsFloat(), decoded));
        }
        return result;
    }

    /// <summary>
    /// UE2's <c>Range</c> struct: a nested tagged list with two <c>Float</c> fields, <c>Min</c> and
    /// <c>Max</c>. Returns null rather than a partial range when either field is missing, the same
    /// contract <see cref="ReadRegion"/> uses for its own nested struct.
    /// </summary>
    private static FloatRange? ReadFloatRange(BioShockPackage package, UnrealProperty property)
    {
        List<UnrealProperty> fields;
        try { fields = UnrealPropertyReader.Read(property.Value, package.Names, out _, start: 0); }
        catch (Exception ex) when (ex is InvalidDataException or IndexOutOfRangeException
                                       or ArgumentOutOfRangeException)
        {
            return null;
        }

        var min = fields.FirstOrDefault(field => field.Name == "Min" && field.Type == UnrealPropertyType.Float);
        var max = fields.FirstOrDefault(field => field.Name == "Max" && field.Type == UnrealPropertyType.Float);
        return min is null || max is null ? null : new FloatRange(min.AsFloat(), max.AsFloat());
    }

    /// <summary>UE2's <c>RangeVector</c> struct: one <see cref="FloatRange"/> per axis, X/Y/Z.</summary>
    private static AxisRange? ReadAxisRange(BioShockPackage package, UnrealProperty property)
    {
        List<UnrealProperty> fields;
        try { fields = UnrealPropertyReader.Read(property.Value, package.Names, out _, start: 0); }
        catch (Exception ex) when (ex is InvalidDataException or IndexOutOfRangeException
                                       or ArgumentOutOfRangeException)
        {
            return null;
        }

        FloatRange? Axis(string name) =>
            fields.FirstOrDefault(field => field.Name == name && field.Type == UnrealPropertyType.Struct) is { } axisField
                ? ReadFloatRange(package, axisField)
                : null;

        var x = Axis("X");
        var y = Axis("Y");
        var z = Axis("Z");
        return x is null || y is null || z is null ? null : new AxisRange(x.Value, y.Value, z.Value);
    }

    /// <summary>
    /// Resolves one object reference, looking first at the actor and then at its class defaults.
    /// <paramref name="expectedClass"/> rejects a reference whose target is of another class, which
    /// is what stops a name-shaped match from standing in for an identity.
    /// </summary>
    private static AssetReference? Reference(
        BioShockPackage package, ClassDefaults defaults, ActorPayload payload, string property, string? expectedClass)
    {
        string origin = "actor";
        var found = payload.Find(property);
        if (found is null)
        {
            found = defaults.Lookup(payload.Export.ClassIndex, property);
            origin = "class defaults";
        }
        if (found is null) return null;

        var index = PropertyValues.AsReference(found);
        if (index is null || index.Value.IsNull) return null;

        return Describe(package, index.Value, origin, expectedClass);
    }

    /// <summary>Resolves a package reference (export or import) to what it names, without reading
    /// its payload. Shared beyond this class by <see cref="Assets.WeaponEffects"/>, which resolves
    /// a weapon class's own <c>Class</c>-typed properties (<c>EmitterClass</c>, <c>LightClass</c>)
    /// the identical way an actor's <c>Object</c>-typed properties resolve here.</summary>
    internal static AssetReference? Describe(
        BioShockPackage package, PackageIndex index, string origin, string? expectedClass)
    {
        string objectName;
        string className;
        SourceId? source = null;

        if (index.IsExport)
        {
            if (index.ExportIndex >= package.Exports.Count) return null;
            var target = package.Exports[index.ExportIndex];
            className = package.GetClassName(target);
            objectName = target.ObjectName;
            if (expectedClass is not null && className != expectedClass) return null;
            source = new SourceId(
                Path.GetFileNameWithoutExtension(package.FilePath), target.Index, className, target.ObjectName);
        }
        else if (index.IsImport)
        {
            if (index.ImportIndex >= package.Imports.Count) return null;
            var import = package.Imports[index.ImportIndex];
            className = import.ClassName;
            objectName = import.ObjectName;
            if (expectedClass is not null && className != expectedClass) return null;
        }
        else return null;

        return new AssetReference
        {
            Index = index,
            ObjectName = objectName,
            ClassName = className,
            Origin = origin,
            Source = source,
        };
    }

    private static IReadOnlyList<AssetReference> ReferenceArray(
        BioShockPackage package, ActorPayload payload, string property)
    {
        if (payload.Find(property) is not { } found) return [];
        var result = new List<AssetReference>();
        foreach (var index in PropertyValues.AsReferenceArray(found))
        {
            if (Describe(package, index, "actor", null) is { } reference) result.Add(reference);
        }
        return result;
    }

    private static LevelContext Summarise(
        BioShockPackage package, string packageName, List<LevelActor> actors, List<SourceId> failed,
        Dictionary<string, int> uninterpreted)
    {
        var staticUsage = new Dictionary<SourceId, List<int>>();
        var skeletalUsage = new Dictionary<SourceId, List<int>>();
        var external = new List<AssetReference>();
        var unresolved = new List<AssetReference>();
        var withoutGeometry = new Dictionary<string, int>(StringComparer.Ordinal);

        for (int i = 0; i < actors.Count; i++)
        {
            var actor = actors[i];

            Record(actor.StaticMesh, staticUsage, i);
            Record(actor.SkeletalMesh, skeletalUsage, i);

            foreach (var reference in Enumerate(actor))
            {
                if (reference.Status == ResolutionStatus.External) external.Add(reference);
                else if (reference.Status == ResolutionStatus.Failed) unresolved.Add(reference);
            }

            if (!actor.HasGeometry)
                withoutGeometry[actor.Source.ClassName] = withoutGeometry.GetValueOrDefault(actor.Source.ClassName) + 1;
        }

        return new LevelContext
        {
            PackageFile = package.FilePath,
            PackageName = packageName,
            ExportCount = package.Exports.Count,
            ImportCount = package.Imports.Count,
            NameCount = package.Names.Count,
            Actors = actors,
            FailedActors = failed,
            StaticMeshUsage = staticUsage,
            SkeletalMeshUsage = skeletalUsage,
            ExternalReferences = external,
            UnresolvedReferences = unresolved,
            ClassesWithoutGeometry = withoutGeometry,
            UninterpretedProperties = uninterpreted,
        };

        static void Record(AssetReference? reference, Dictionary<SourceId, List<int>> usage, int actorIndex)
        {
            if (reference?.Source is not { } source) return;
            if (!usage.TryGetValue(source, out var users)) usage[source] = users = [];
            users.Add(actorIndex);
        }

        static IEnumerable<AssetReference> Enumerate(LevelActor actor)
        {
            if (actor.StaticMesh is not null) yield return actor.StaticMesh;
            if (actor.SkeletalMesh is not null) yield return actor.SkeletalMesh;
            if (actor.Brush is not null) yield return actor.Brush;
            foreach (var skin in actor.MaterialOverrides) yield return skin;
        }
    }

    /// <summary>
    /// The bounding box of every actor that has a position. Cheap sanity check on a level: Medical
    /// Pavilion should be tens of thousands of centimetres across, not millions.
    /// </summary>
    public static (Vector3 Min, Vector3 Max) Bounds(IEnumerable<LevelActor> actors)
    {
        var min = new Vector3(float.MaxValue);
        var max = new Vector3(float.MinValue);
        bool any = false;

        foreach (var actor in actors)
        {
            if (!actor.Transform.Present.Contains("Location")) continue;
            min = Vector3.Min(min, actor.Transform.Location);
            max = Vector3.Max(max, actor.Transform.Location);
            any = true;
        }

        return any ? (min, max) : (Vector3.Zero, Vector3.Zero);
    }
}
