"""Validate a BioShockStudio level manifest before a UE5 import.

This is deliberately dependency-free so it can run in CI or before opening Unreal:

    py tools/ue5/validate_level_manifest.py C:\\exports\\1-Medical.level.json

It does not claim to import gameplay actors. Instead it produces an explicit report of actors that
the current UE5 bridge can create as geometry and those retained as typed placeholders, which keeps
the source map's object graph visible while specialised importers are added.
"""

import json
import os
import sys
from collections import Counter


SUPPORTED_VERSION = 3


def validate(path):
    with open(path, "r", encoding="utf-8") as handle:
        level = json.load(handle)

    version = level.get("formatVersion")
    if version != SUPPORTED_VERSION:
        raise ValueError(
            "unsupported level manifest version {!r}; expected {}".format(version, SUPPORTED_VERSION))

    actors = level.get("actors", [])
    coverage = level.get("actorCoverage", [])
    if len(actors) == 0:
        raise ValueError("manifest contains no actor graph")

    by_status = Counter()
    for row in coverage:
        for status, count in row.get("status", {}).items():
            by_status[status] += count

    covered = sum(by_status.values())
    if covered != len(actors):
        raise ValueError("coverage accounts for {} actors but manifest contains {}".format(covered, len(actors)))

    keys = [actor["key"] for actor in actors]
    if len(set(keys)) != len(keys):
        raise ValueError("actor keys are not unique")

    actor_keys = set(keys)
    instances = level.get("instances", [])
    assets = {asset.get("key"): asset for asset in level.get("assets", [])}
    missing_instance_owners = [item.get("actorKey") for item in instances
                               if item.get("actorKey") not in actor_keys
                               and assets.get(item.get("asset"), {}).get("kind") != "BuiltWorld"]
    if missing_instance_owners:
        raise ValueError("{} instances lack a valid actor key".format(len(missing_instance_owners)))

    lights = level.get("lights", [])
    missing_light_sources = [light.get("key") for light in lights if light.get("key") not in actor_keys]
    if missing_light_sources:
        raise ValueError("{} lights lack a valid source actor key".format(len(missing_light_sources)))

    material_sections = [
        section for asset in level.get("assets", []) for section in asset.get("sections", [])
        if section.get("material") is not None
    ]
    incomplete_materials = [
        section for section in material_sections
        if not all(section.get(field) is not None for field in
                   ("materialKey", "materialPackage", "materialClassName", "materialExportIndex"))
    ]
    if incomplete_materials:
        raise ValueError(
            "{} named sections lack a material source identity".format(len(incomplete_materials)))

    navigation = [actor["navigation"] for actor in actors if actor.get("navigation") is not None]
    navigation_references = [reference for item in navigation
                             for reference in item.get("pathLinks", []) + item.get("autoGeneratedFlyingPathNodes", [])]
    if any(reference is None or reference.get("index") == 0 for reference in navigation_references):
        raise ValueError("a navigation reference is null or has a zero package index")

    scripts = [actor["scriptActions"] for actor in actors if actor.get("scriptActions") is not None]
    incomplete_scripts = [script for script in scripts if not script.get("complete")]
    action_references = [reference for script in scripts for reference in script.get("actions", [])]
    if any(reference is None or reference.get("index") == 0 for reference in action_references):
        raise ValueError("a script action reference is null or has a zero package index")

    emitters = [actor["emitters"] for actor in actors if actor.get("emitters") is not None]
    incomplete_emitters = [emitter for emitter in emitters if not emitter.get("complete")]
    emitter_templates = [template for emitter in emitters for template in emitter.get("templates", [])]
    emitter_references = [template.get("source") for template in emitter_templates]
    if any(reference is None or reference.get("index") == 0 for reference in emitter_references):
        raise ValueError("an emitter template reference is null or has a zero package index")
    emitter_materials = [template.get("material") for template in emitter_templates
                         if template.get("material") is not None]
    if any(material.get("index") == 0 for material in emitter_materials):
        raise ValueError("an emitter material reference has a zero package index")

    geometry_statuses = ("GeometryInScene", "SkeletalMeshBindPose")
    geometry_actors = sum(by_status[status] for status in geometry_statuses)

    return {
        "formatVersion": version,
        "package": level["package"],
        "actors": len(actors),
        "instances": len(instances),
        "lights": len(lights),
        "geometryActors": geometry_actors,
        "placeholderActors": len(actors) - geometry_actors,
        "status": dict(sorted(by_status.items())),
        "rawProperties": sum(len(actor.get("properties", [])) for actor in actors),
        "materialBoundSections": len(material_sections),
        "materialSourceIdentities": len(material_sections) - len(incomplete_materials),
        "navigationActors": len(navigation),
        "navigationReferences": len(navigation_references),
        "scriptActors": len(scripts),
        "scriptActionReferences": len(action_references),
        "incompleteScriptActionArrays": len(incomplete_scripts),
        "emitterActors": len(emitters),
        "emitterTemplateReferences": len(emitter_references),
        "emitterMaterialReferences": len(emitter_materials),
        "incompleteEmitterArrays": len(incomplete_emitters),
    }


def main(argv):
    if len(argv) != 2:
        raise SystemExit("usage: validate_level_manifest.py <level.json>")

    report = validate(argv[1])
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print("level manifest validation failed: {}".format(error), file=sys.stderr)
        raise SystemExit(1)
